app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('mysite.urls', namespace='mysite')),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

app/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', views.logout, name='logout'),
    path('anon/', views.ForAnonymUser.as_view(), name='anon'),
    path('profile-other-user/<slug:other_user>/', views.ProfileOtherUser.as_view(), name='other_user'),
]

app/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
    status = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'User'
        
    def __str__(self):
        return self.username
    
    def get_absolute_url(self):
        return reverse("users:other_user", args=[self.username])
    

app/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()
    
    class Meta:
        model = User
        fields = ('username', 'password')
        
        
class UserRegistrationForm(UserCreationForm):
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
        
class ProfileForm(forms.ModelForm):
    username = forms.CharField()
    email = forms.CharField()
    class Meta:
        model = User
        fields = ('username', 'email', 'status')

app/users/views.py
# from django.db.models.base import Model as Model
from django.shortcuts import redirect, get_object_or_404
from django.contrib import auth
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, UpdateView
from django.contrib.auth.views import LoginView

from .forms import UserLoginForm, UserRegistrationForm, ProfileForm
from .models import User
from mysite.models import Game


# def login(request):
    
#     if request.method == 'POST':
#         form = UserLoginForm(data=request.POST)
#         if form.is_valid():
#             username = request.POST['username']
#             password = request.POST['password']
#             user = auth.authenticate(username=username, password=password)
#             if user:
#                 messages.success(request, f"{user.username} Вы успешно вошли в аккаунт!")
#                 auth.login(request, user)
#                 return HttpResponseRedirect(reverse('mysite:home'))
#     else:
#         form = UserLoginForm()
    
#     context = {
#         'title': 'Авторизация',
#         'form': form,
#     }
    
#     return render(request, 'users/login.html', context)


class UserLoginView(LoginView):
    template_name = "users/login.html"
    form_class = UserLoginForm
    extra_context = {'title': 'Авторизация'}
    
    def get_success_url(self):
        redirect_page = self.request.POST.get('next', None)
        if redirect_page and redirect_page != reverse('users:logout'):
            return redirect_page
        return reverse_lazy("mysite:home")


# def register(request):
#     if request.method == 'POST':
#         form = UserRegistrationForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('users:login')
#     else:
#         form = UserRegistrationForm()
    
#     context = {
#         'title': 'Регистрация',
#         'form': form,
#     }
    
#     return render(request, 'users/register.html', context)


class UserRegistrationView(CreateView):
    template_name = "users/register.html"
    form_class = UserRegistrationForm
    success_url = reverse_lazy("mysite:home")
    extra_context = {'title': 'Регистрация'}
    
    def form_valid(self, form):
        user = form.instance
        
        if user:
            form.save()
            auth.login(self.request, user=user)
            
        return redirect(self.success_url)


# def profile(request):
#     if request.method == 'POST':
#         form = ProfileForm(data=request.POST, instance=request.user)
#         if form.is_valid():
#             form.save()
#             return redirect('users:profile')
#     else:
#         form = ProfileForm(instance=request.user)
        
#     context = {
#         'title': "Профиль",
#         'form': form
#     }
    
#     return render(request, 'users/profile.html', context)


class UserProfileView(UpdateView):
    template_name = "users/profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy("users:profile")
    extra_context = {'title': 'Профиль'}
    
    def get_object(self, queryset=None):
        return self.request.user


def logout(request):
    auth.logout(request)
    return redirect(reverse('users:login'))


class ForAnonymUser(TemplateView):
    template_name = "users/for_anonym_user.html"
    
    
# def profile_other_user(request, other_user):
#     context = {
#         'user': get_object_or_404(User.objects.values('username', 'email'), username=other_user),
#         'posts': Game.objects.select_related('category', 'avtor').filter(avtor__username=other_user)
#     }
    
#     return render(request, "users/profile_other_user.html", context)


class ProfileOtherUser(ListView):
    template_name = "users/profile_other_user.html"
    context_object_name = "posts"
    
    def get_queryset(self):
        return Game.objects.filter(avtor__username=self.kwargs["other_user"]).select_related('category', 'avtor')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = get_object_or_404(User.objects.values('username', 'email'), username=self.kwargs['other_user'])
        return context
    
    
    
    

app/users/templates/users/for_anonym_user.html
<h2>Публиковать посты могуть только зарегистрировавшиеся пользователи <a href="{% url "users:register" %}">Зарегиться</a></h2>

app/users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static "users/css/login.css" %}">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css">
</head>
<body>
    <div class="container">
        <h1>Авторизация</h1>

        <form action="{% url "users:login" %}" method='post'>
            {% csrf_token %}

            {% if request.GET.next %}
            <input type="hidden" name="next" value={{ request.GET.next}}>
            {% endif %}

            <div class="input-type">
                <i class="bx bxs-user"></i>
                <input type="text" placeholder="Имя пользователя" name='username' id='id_username'>
                {% if form.username.errors %}{{ form.username.errors }}{% endif %}
            </div>

            <div class="input-pass">
                <i class="bx bxs-lock-alt"></i>
                <input type="password" placeholder="Пароль", name='password', id='id_password'>
                {% if form.password.errors %}{{ form.password.errors }}{% endif %}
            </div>

            <div class="remember-forgot">
                <label for="#"><input type="checkbox">Запомнить меня</label>
                <a href="#">Забыли пароль?</a>
            </div>

            <button type="submit" class="login-btn">Войти</button>

            <div class="register-link">
                <p>У вас нет учетной записи?<a href="{% url "users:register" %}">Зарегистрироваться </a></p>
            </div>
        </form>
    </div>

</body>
</html>

app/users/templates/users/profile.html
{% extends "mysite/index.html" %}

{% block content %}
<h2>
    <form action="{% url "users:profile" %}" method='post'>
        {% csrf_token %}
        {% comment %} <input type="text" name='username' id="id_username" placeholder="Имя" value={{ form.username.value }} required>
        {% if form.username.errors %}{{ form.username.errors }}{% endif %}
        <input type="text" name='email' id="id_email" placeholder="Почта" value={{ form.email.value }} required>
        {% if form.email.errors %}{{ form.email.errors }}{% endif %}
        <div>
            <label for="id_status">Статус</label><br>
            <input type="checkbox" name='status', id="id_status" value={{form.status.value}} {% if form.status.value %}checked{% endif %} required>
        </div> {% endcomment %}
        {{ form.as_p }}
        <button class="btn btn-outline-secondary" type='submit'>Сохранить</button>
    </form>
</h2>
{% endblock content %}

app/users/templates/users/profile_other_user.html
{% extends "mysite/base.html" %}

{% block content %}
<h1>Посты пользователь - {{ user.username }}</h1>
<h3>
    {{ user.email }}
</h3><br><br>




{% for post in posts %}
<h2>{{ post.name }}</h2><p>Категория - {{ post.category.name }}</p><br>
{% if post.iamge %}
<img src="#" alt="#">
{% endif %}
<p>{{ post.description }}</p>

<p>Время публикации: {{ post.time_created }}</p>

<a href="{{ post.get_absolute_url }}"><button class="btn btn-outline-secondary">Подробнее</button></a>
<p>______________________________________________________</p>

{% endfor %}
{% endblock content %}

app/users/templates/users/register.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "users/css/register.css" %}">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css">
    <title>{{ title }}</title>
</head>
<body>
    <div class="container">
        <h1>Регистрация</h1>
        <form action="{% url "users:register" %}" method="POST">
            {% csrf_token %}
            <div class="input-type">
                <i class='bx bx-user'></i>
                <input type="text" placeholder="Имя пользователя" name="username" id="id_username" required>
                {% if form.username.errors %}{{ form.username.errors }}{% endif %}
            </div>
            <div class="input-type">
                <i class='bx bx-envelope'></i>
                <input type="email" placeholder="Email" name="email" id="id_email" required>
                {% if form.email.errors %}{{ form.email.errors }}{% endif %}
            </div>
            <div class="input-pass">
                <i class='bx bx-lock'></i>
                <input type="password" placeholder="Пароль" name="password1" id="id_password1" required>
                {% if form.password1.errors %}{{ form.password1.errors }}{% endif %}
            </div>
            <div class="input-pass">
                <i class='bx bx-lock'></i>
                <input type="password" placeholder="Подтверждение пароля" name="password2" id="id_password2" required>
                {% if form.password2.errors %}{{ form.password2.errors }}{% endif %}
            </div>
            <div class="remember-forgot">
                <a href="#"></a>
            </div>
            <button type="submit" class="login-btn">Зарегистрироваться</button>
        </form>
        <div class="register-link">
            <p>Уже есть аккаунт? <a href="{% url "users:login" %}">Войти</a></p>
        </div>
    </div>
</body>
</html>