app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('mysite.urls', namespace='mysite')),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

app/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('add-post/', views.AddPostView.as_view(), name='add_post'),
    path('delete-post/<int:game_id>/', views.del_post, name='del_post'),
    path('my-post/', views.MyPostsView.as_view(), name='my_posts'),
]

app/mysite/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from unidecode import unidecode

from users.models import User


class Game(models.Model):
    name = models.CharField(max_length=150, verbose_name="Название")
    slug = models.SlugField(unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, default='Нет описания', verbose_name="Описание")
    iamge = models.ImageField(upload_to='foto', blank=True, max_length=1000, verbose_name="Изображение")
    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Время публикации")
    category = models.ForeignKey(to="CategoryGame", on_delete=models.CASCADE, verbose_name="Категория")
    avtor = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Автор', blank=True, null=True)
    
    class Meta:
        ordering = ['-time_created']
        db_table = 'Game'
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("mysite:game_details", args=[self.slug])
    
    # полезная хуйня
    def save(self, *args, **kwargs):
        num = 1
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        while Game.objects.filter(slug=self.slug).exists():
            self.slug = f"{self.slug}-{num}"
            num += 1
        super().save(*args, **kwargs)
    
    
    
class CategoryGame(models.Model):
    name = models.CharField(max_length=150, verbose_name="Название")
    slug = models.SlugField(unique=True, blank=True, null=True, verbose_name="URL")
    
    class Meta:
        db_table = "CategoryGame"
        
    def __str__(self):
        return self.name
    
    
    

app/posts/models.py
from django.db import models

from users.models import User
from mysite.models import Game

app/posts/forms.py
from typing import Any
from django import forms

from mysite.models import Game, CategoryGame


class AddPostForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=CategoryGame.objects.all())
    
    class Meta:
        model = Game
        fields = ('name', 'description', 'category')

app/posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView

from .forms import AddPostForm
from mysite.models import Game


# @login_required(login_url="users:anon")
# def add_post(request):
#     if request.method == 'POST':
#         form = AddPostForm(data=request.POST)
#         if form.is_valid():
#             avtor = form.save(commit=False)
#             avtor.avtor = request.user
#             avtor.save()
            
#             return redirect('mysite:home')
#     else:
#         form = AddPostForm()
            
#     context = {
#         'title': "Добавить пост",
#         'form': form,
#     }
    
#     return render(request, 'posts/add_post.html', context)


class AddPostView(LoginRequiredMixin, CreateView):    
    form_class = AddPostForm
    template_name = 'posts/add_post.html'
    extra_context = {'title': 'Создать пост'}
    
    def form_valid(self, form):
        avtor = form.save(commit=False)
        avtor.avtor = self.request.user
        print(avtor.slug)
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return reverse_lazy('mysite:home')


def del_post(request, game_id):
    post = get_object_or_404(Game, id=game_id, avtor=request.user)
    post.delete()
    return redirect("mysite:home")


# class DeletePostView(LoginRequiredMixin, DeleteView):


# login_required(login_url='users:login')
# def my_posts(request):
    
#     context = {
#         'posts': Game.objects.filter(avtor=request.user).select_related('category', 'avtor'),
#         'title': "Мои публикаци",
#     }
    
#     return render(request, 'posts/my_posts.html', context)
    
    
class MyPostsView(LoginRequiredMixin, ListView):
    template_name = 'posts/my_posts.html'
    context_object_name = 'posts'
    extra_context = {'title': "Мои публикаци"}
    
    def get_queryset(self):
        return Game.objects.filter(avtor=self.request.user).select_related('category', 'avtor')


# <form action="https://www.google.com/search" method="get">
#         <label for="search">Поиск:</label>
#         <input type="text" id="search" name="q" placeholder="Введите запрос" required>
#         <button type="submit">Поиск</button>
#     </form>

app/posts/templates/posts/add_post.html
{% extends "mysite/base.html" %}
{% load mytags %}


{% block content %}
<h3>
    <form action="{% url "posts:add_post" %}" method="post">
        {% csrf_token %}
        {% comment %} <input type="text" placeholder="Название" name="name" id="id_name" required>
        {% if form.name.errors %}{{ form.name.errors }}{% endif %}
        <input type="text" placeholder="URL" name="slug" id="id_slug" required>
        {% if form.slug.errors %}{{ form.slug.errors }}{% endif %}
        <input type="text" placeholder="Описание" name="description" id="id_description" required>
        {% if form.description.errors %}{{ form.description.errors }}{% endif %}
        <select name="category" id="id_category" required>
            <option value="">Выберите категорию</option>  <!-- Опция по умолчанию -->
            {% tag_categories as categories%}
            {% for i in categories %}
                <option value="{{ i.id }}">{{ i.name }}</option>  <!-- Используй category.pk для value -->
            {% endfor %}
        </select> {% endcomment %}
        {{ form.as_p }}  
        <button type="submit">Отправить</button>
    </form>
</h3>
{% endblock content %}

app/posts/templates/posts/my_posts.html
{% extends "mysite/base.html" %}

{% block content %}

{% if posts %}
{% for post in posts %}
<h2>{{ post.name }}</h2><p>Категория - {{ post.category.name }}</p><br>
{% if post.iamge %}
<img src="#" alt="#">
{% endif %}
<p>{{ post.description }}</p><br>

<p>Автор - {{ post.avtor.username }} </p>

<p>Время публикации: {{ post.time_created }}</p>

<a href="{{ post.get_absolute_url }}"><button class="btn btn-outline-secondary">Подробнее</button></a>
{% if post.avtor == request.user %}
<form action="{% url "posts:del_post" game_id=post.id %}" method='post'>
    {% csrf_token %}
    <a href="{% url "posts:del_post" game_id=post.id %}"><button class="btn btn-outline-secondary">Удалить</button></a>
</form>
{% endif %}
<p>-----------------------------------------------</p>

{% endfor %}
{% else %}
<h1>
    У вас нет опубликованных постов
</h1>
{% endif %}

{% endblock content %}