app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('mysite.urls', namespace='mysite')),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

app/mysite/urls.py
from django.urls import path

from . import views


app_name = 'mysite'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('search/', views.IndexView.as_view(), name='search'),
    path('category/<slug:category_slug>/', views.GameCategoryView.as_view(), name='category'),
    path('game/<slug:game_slug>/', views.GameDetailsView.as_view(), name='game_details'),
]

app/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('add-post/', views.AddPostView.as_view(), name='add_post'),
    path('delete-post/<int:game_id>/', views.del_post, name='del_post'),
    path('my-post/', views.MyPostsView.as_view(), name='my_posts'),
]

app/users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', views.logout, name='logout'),
    path('anon/', views.ForAnonymUser.as_view(), name='anon'),
    path('profile-other-user/<slug:other_user>/', views.ProfileOtherUser.as_view(), name='other_user'),
]

app/mysite/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from unidecode import unidecode

from users.models import User


class Game(models.Model):
    name = models.CharField(max_length=150, verbose_name="Название")
    slug = models.SlugField(unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, default='Нет описания', verbose_name="Описание")
    iamge = models.ImageField(upload_to='foto', blank=True, max_length=1000, verbose_name="Изображение")
    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Время публикации")
    category = models.ForeignKey(to="CategoryGame", on_delete=models.CASCADE, verbose_name="Категория")
    avtor = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Автор', blank=True, null=True)
    
    class Meta:
        ordering = ['-time_created']
        db_table = 'Game'
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("mysite:game_details", args=[self.slug])
    
    # полезная хуйня
    def save(self, *args, **kwargs):
        num = 1
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        while Game.objects.filter(slug=self.slug).exists():
            self.slug = f"{self.slug}-{num}"
            num += 1
        super().save(*args, **kwargs)
    
    
    
class CategoryGame(models.Model):
    name = models.CharField(max_length=150, verbose_name="Название")
    slug = models.SlugField(unique=True, blank=True, null=True, verbose_name="URL")
    
    class Meta:
        db_table = "CategoryGame"
        
    def __str__(self):
        return self.name
    
    
    

app/mysite/views.py
from django.views.generic import ListView, DetailView

from .models import Game
from .utils import q_search

# def index(request):
#     game = Game.objects.all().select_related('category', 'avtor')
    
#     context = {
#         'title': 'Главная страница',
#         'games': game,
#     }
    
#     return render(request, 'mysite/index.html', context)


class IndexView(ListView):
    template_name = "mysite/index.html"
    context_object_name = "games"
    extra_context = {'title': "Главная страница"}
    
    def get_queryset(self):
        query = self.request.GET.get('q', None)
        if query:
            game = q_search(query)
        else:
            game = Game.objects.all().select_related('category', 'avtor')
            
        return game


# def category(request, category_slug):
#     category = get_object_or_404(CategoryGame, slug=category_slug)
#     post = Game.objects.filter(category_id=category.pk).select_related('category', 'avtor')
    
#     context = {
#         'title': f"категория - {category.name}",
#         'posts': post,
#     }
    
#     return render(request, 'mysite/category.html', context)


class GameCategoryView(ListView):
    template_name = "mysite/category.html"
    context_object_name = 'posts'
    allow_empty = False
    
    def get_queryset(self):
        return Game.objects.filter(category__slug=self.kwargs['category_slug']).select_related('category', 'avtor')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = context['posts'][0].category
        context["title"] = f"категория - {category}"
        return context


# def game_details(request, game_id, game_slug):
#     game = get_object_or_404(Game.objects.select_related('category', 'avtor'), id=game_id, slug=game_slug)
    
#     return render(request, 'mysite/game_details.html', {'title': game.name, 'game': game})


class GameDetailsView(DetailView):
    template_name = "mysite/game_details.html"
    slug_url_kwarg = 'game_slug'
    context_object_name = 'game'
    
    def get_object(self, queryset=None):
        game = Game.objects.select_related('category', 'avtor').get(slug=self.kwargs[self.slug_url_kwarg])
        return game
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        return context

app/mysite/templates/mysite/base.html
{% load static %}
{% load mytags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "mysite/css/style.css" %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <title>{{ title }}</title>
</head>
<body>
    <a href="{% url "mysite:home" %}" class="home"><h1>На главную</h1></a>
    <h2>{{ title }}</h2>
    <a href="{% url "posts:add_post" %}">Добавить пост</a>
    <a href="{% url "posts:my_posts" %}">мои посты</a>

    <form action="{% url "mysite:search" %}" method='get' role='search'>
        <label for="search">Поиск по нику: '@username'</label>
        <input type="search" placeholder="Поиск" name="q">
        <button type="submit">Найти</button>
    </form>

    <details>
        <summary><h2>Категории</h2></summary>
            <ul>
                {% tag_categories as categories%}
                {% for category in categories %}
                <li><a href="{% url "mysite:category" category_slug=category.slug %}"><button type='submit' class="btn btn-outline-secondary">{{ category.name }}</button></a></li>
                {% endfor %}
            </ul>
    </details>

    <p class="bt-login">
        {% if request.user.is_authenticated %}
        <a href="{% url "users:logout" %}" class='login'>Выйти</a>
        <a href="{% url "users:profile" %}">Профиль</a>
        {% else %}
        <a href="{% url "users:login" %}" class='login'>Войти</a>
        {% endif %}
    </p>

    {% block content %}{% endblock content %}

    
    
</body>
</html>

app/mysite/templates/mysite/category.html
{% extends "mysite/base.html" %}

{% block content %}
{% for post in posts %}
<h2>{{ post.name }}</h2><p>Категория - {{ post.category__name }}</p><br>
{% if post.iamge %}
<img src="#" alt="#">
{% endif %}
<p>{{ post.description }}</p><br>

{% if request.user.is_authenticated %}
<p>Автор - {{ post.avtor__username }}</p>
{% else %}
<p>Автор - Аноним</p>
{% endif %}

<p>Время публикации: {{ post.time_created }}</p>

<a href="{% url "mysite:game_details" game_slug=post.slug %}"><button class="btn btn-outline-secondary">Подробнее</button></a>
{% comment %} <form action="{% url "posts:del_post" %}">
    {% csrf_token %}
    <button class="btn btn-outline-secondary">Удалить</button>
</form> {% endcomment %}
<p>-----------------------------------------------</p>

{% endfor %}
{% endblock content %}

{% comment %} {% block content %}
{% include "mysite/index.html" %}
{% endblock content %} {% endcomment %}

app/mysite/templates/mysite/game_details.html
{% extends "mysite/base.html" %}

{% block content %}

<h2>{{ game.name }}</h2><p>Категория - {{ game.category.name }}</p><br>
{% if game.iamge %}
<img src="#" alt="#">
{% endif %}
<p>{{ game.description }}</p><br>

<p>Автор - {{ game.avtor.username }}</p>

<p>Время публикации: {{ game.time_created }}</p>

{% if game.avtor == request.user %}
<form action="{% url "posts:del_post" game_id=game.id %}" method='post'>
    {% csrf_token %}
    <a href="{% url "posts:del_post" game_id=game.id %}"><button class="btn btn-outline-secondary">Удалить</button></a>
</form>

{% endif %}
{% endblock content %}

app/mysite/templates/mysite/index.html
{% extends "mysite/base.html" %}

{% block content %}

{% for game in games %}
<h2>{{ game.name }}</h2><p>Категория - {{ game.category.name }}</p><br>
{% if game.iamge %}
<img src="#" alt="#">
{% endif %}
<p>{{ game.description }}</p><br>

<p>
    Автор - 
    {% if game.avtor.username == request.user.username %}
    {{ game.avtor.username }}
    {% else %}
    <a href="{{ game.avtor.get_absolute_url }}">
        {{ game.avtor.username }}
    </a>
    {% endif %}
</p>

<p>Время публикации: {{ game.time_created }}</p>

<a href="{{ game.get_absolute_url }}"><button class="btn btn-outline-secondary">Подробнее</button></a>
{% if game.avtor == request.user %}
<form action="{% url "posts:del_post" game_id=game.id %}" method='post'>
    {% csrf_token %}
    <a href="{% url "posts:del_post" game_id=game.id %}"><button class="btn btn-outline-secondary">Удалить</button></a>
</form>
{% endif %}
<p>-----------------------------------------------</p>

{% endfor %}
{% endblock content %}